### ISSUE TITLE
Creating torrents

### ISSUE THREAD

**Issue by LayerCorp** [captainswain/Transmission-EasySeedbox#1]
Hi, thanks for this project!

Is there any help to create torrents using this GUI please? I suppose that first I need to create ftp daemon and upload the files via ftp, and then create the torrent with the GUI... but cant find any button for that.

If you can help me with easy steps for the ftp thing would be great too!

Im using ubuntu 16 64bit

**Comment by captainswain** [comment]
Hi,

In order to create torrents using Transmission, you will have to use the `transmission-create ` command in your terminal. For some reason, they don't include this within the web interface.

## Uploading your files
My recommendation for uploading your files is using SFTP with your server login. I can recommend you check out FileZilla to make your life a bit easier. Note that when you are using sftp your port is 22 ( the same as ssh).
Here is an example as to what that would look like:
![screen shot 2017-06-15 at 7 57 36 pm](https://user-images.githubusercontent.com/808890/27210112-f06fc964-5204-11e7-94de-d0c233d6aef1.png)

Once you are logged in simply drag and drop the file(or folder) you want to create the torrent for into the remote directory of your choice (I chose to upload my file to `/home/downloads/downloaded`).




## Creating the torrent
First and foremost you need to log into your server using ssh.


Then navigate to the folder you uploaded the file(s) to.
`cd /home/downloads/downloaded`

Then you use the `transmission-create` command to create the torrent file:

`
transmission-create -o myTorrent.torrent -c "This is a comment about my torrent" -t udp://tracker.openbittorrent.com:80 -t udp://open.demonii.com:1337 -t udp://tracker.coppersurfer.tk:6969 -t udp://tracker.leechers-paradise.org:6969 ubuntu-16.04.2-desktop-i386.iso
`
For a breakdown of the command usage, you can check out:
https://help.ubuntu.com/community/TransmissionHowTo#Transmission_Create

hope this helped a bit!

**Comment by LayerCorp** [comment]
Thanks for your help and time!

Im ok with that guide ;) but is very sad that with transmission webgui is not possible to create torrents :( the whole idea of using the webgui is not to use command line interface.

Do you know if is there some plugin or modified version of transmission with create torrents option built in?

If not, can you recommend me some other client with webgui who allow me to create torrent and the install process is easy? I love EasySeedbox, installed it some times yet without any problem, just this one who is not from your script.

Im trying to install now the arakasi72/rtinst script and is giving me many problems, cant install yet. I even changed OS and nothing.

**Comment by captainswain** [comment]
I agree! It is very sad that the feature is not included. There is no plugin that I'm aware of that will add the functionality to the transmission web interface. 

I can recommend you check out rtorrent/rutorrent. 

A great script to install rtorrent is Quickbox, you can find it at https://quickbox.io/
